apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  namespace: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      module: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        module: api
    spec:
      containers:
      - image: hands-on_api:latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "300Mi"
            cpu: "200m"
        imagePullPolicy: IfNotPresent
        name: container-api
        ports:
        - name: p-api
          containerPort: 8989
        command: ["python3", "/app/api.py"]
