apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: demo
spec:
  ports:
    - port: 8989
      targetPort: p-api
      nodePort: 30021
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    module: api