apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webapp
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      module: webapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        module: webapp
    spec:
      containers:
      - image: hands-on_webapp:latest
        env:
        - name: INSTANCE_STATUS
          value: Staging
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "300Mi"
            cpu: "200m"
        imagePullPolicy: IfNotPresent
        name: container-webapp
        ports:
        - name: p-webapp
          containerPort: 80
