apiVersion: v1
kind: Service
metadata:
  name: service-webapp
  namespace: demo
spec:
  ports:
    - port: 80
      targetPort: p-webapp
      nodePort: 30023
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    module: webapp